"""migrate database

Revision ID: 20fbfdcfa9c9
Revises: 
Create Date: 2020-05-21 18:49:27.758183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20fbfdcfa9c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_customer', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_pet_customer_id'), ['id'])

    with op.batch_alter_table('pet_employee', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_pet_employee_id'), ['id'])
        batch_op.drop_index('ix_pet_employee_Ename')
        batch_op.create_index(batch_op.f('ix_pet_employee_Ename'), ['Ename'], unique=False)

    with op.batch_alter_table('pet_medicine', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_pet_medicine_id'), ['id'])
        batch_op.drop_index('ix_pet_medicine_Mname')
        batch_op.create_index(batch_op.f('ix_pet_medicine_Mname'), ['Mname'], unique=False)

    with op.batch_alter_table('pet_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pet_order_Oaddress'), ['Oaddress'], unique=False)
        batch_op.create_index(batch_op.f('ix_pet_order_Oname'), ['Oname'], unique=False)

    with op.batch_alter_table('pet_pet', schema=None) as batch_op:
        batch_op.drop_index('ix_pet_pet_Pname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_pet', schema=None) as batch_op:
        batch_op.create_index('ix_pet_pet_Pname', ['Pname'], unique=1)

    with op.batch_alter_table('pet_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pet_order_Oname'))
        batch_op.drop_index(batch_op.f('ix_pet_order_Oaddress'))

    with op.batch_alter_table('pet_medicine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pet_medicine_Mname'))
        batch_op.create_index('ix_pet_medicine_Mname', ['Mname'], unique=1)
        batch_op.drop_constraint(batch_op.f('uq_pet_medicine_id'), type_='unique')

    with op.batch_alter_table('pet_employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pet_employee_Ename'))
        batch_op.create_index('ix_pet_employee_Ename', ['Ename'], unique=1)
        batch_op.drop_constraint(batch_op.f('uq_pet_employee_id'), type_='unique')

    with op.batch_alter_table('pet_customer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_pet_customer_id'), type_='unique')

    # ### end Alembic commands ###
